### ISSUE TITLE
保存之后输出的文件没有变化（缓存里的也是）

### ISSUE THREAD

**Issue by shenfu57** [kkr223/limbusTranslator#3]
https://user-images.githubusercontent.com/126936779/223430097-a1bda06b-cffe-4ecc-861f-0f7c3dec2c9a.mp4

保存之后输出的文件没有变化（缓存里的也是）

**Comment by kkr223** [comment]
> 保存之后输出的文件没有变化（缓存里的也是）

trt文件掉了，明天修

**Comment by kkr223** [comment]
> 保存之后输出的文件没有变化（缓存里的也是）

问题不大，修了
